data:
  train_path: "datasets/cleaned_data/mkt_camp_v1/train.csv"
  test_path: "datasets/cleaned_data/mkt_camp_v1/test.csv"
  target_column: "Response"

model:
  name: "knn"
  save_path: "model_checkpoints/knn_model.pkl"
  params:
    n_neighbors: 30

evaluation:
  save_path: "results/knn_results.json"
  hyperparameter_tuning_save_path: "results/hyper_parameter_tuning_knn_results.json"