data:
  train_path: "datasets/cleaned_data/mkt_camp_v1/train.csv"
  test_path: "datasets/cleaned_data/mkt_camp_v1/test.csv"
  target_column: "Response"

model:
  name: "svm"
  save_path: "model_checkpoints/svm_model.pkl"
  params:
    kernel: "linear"
    C: 3
    gamma: "auto"

evaluation:
  save_path: "results/svm_results.json"
  hyperparameter_tuning_save_path: "results/hyper_parameter_tuning_svm_results.json"